import { Nunito, Poppins } from "next/font/google";
import "./globals.css";

const poppinsSans = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins-sans",
  display: "swap",
});

const nunitoSans = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  display: "swap",
});

export const metadata = {
  title: "Revbix HR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.className} ${nunitoSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
